# Generated by Django 5.1.2 on 2024-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_otelmemnuniyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='otelmemnuniyet',
            name='cihaz_bilgisi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otelmemnuniyet',
            name='ip_adresi',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otelmemnuniyet',
            name='konum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otelmemnuniyet',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='memnuniyet_resimleri/'),
        ),
        migrations.AddField(
            model_name='otelmemnuniyet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='memnuniyet_videolari/'),
        ),
    ]
