# Generated by Django 5.1.2 on 2024-10-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_onayli_otelmemnuniyet_yayinla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otelmemnuniyet',
            old_name='yayinla',
            new_name='yayınla',
        ),
    ]
