# Generated by Django 5.1.2 on 2024-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_yayinla_otelmemnuniyet_yayınla'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresi', models.GenericIPAddressField()),
                ('cihaz_bilgisi', models.CharField(max_length=255)),
                ('konum', models.CharField(blank=True, max_length=255, null=True)),
                ('ziyaret_tarihi', models.DateTimeField(auto_now_add=True)),
                ('buton_tiklama_sayisi', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ziyaretçi Logu',
                'verbose_name_plural': 'Ziyaretçi Logları',
            },
        ),
    ]
