# Generated by Django 5.1.2 on 2024-10-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_visitorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={},
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='cihaz_bilgisi',
            new_name='device_info',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='ip_adresi',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='konum',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='ziyaret_tarihi',
            new_name='visit_time',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='buton_tiklama_sayisi',
        ),
    ]
