# Generated by Django 5.1.2 on 2024-10-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_visitorlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='İzleyizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'İzleyici',
                'verbose_name_plural': 'İzleyici',
            },
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
    ]
