# Generated by Django 5.1.2 on 2024-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_i_zleyizi_delete_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Fotoğraf')),
                ('alt_text', models.CharField(help_text='Görselin SEO için açıklaması', max_length=200, verbose_name='Alt Metin')),
                ('slug', models.SlugField(help_text='SEO için başlığa uygun bir kısa URL yapısı', max_length=200, unique=True, verbose_name='URL Yapısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-created_at'],
            },
        ),
    ]
