# Generated by Django 5.1.2 on 2024-11-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_videogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='end_time',
            field=models.IntegerField(default=10, verbose_name='Bitiş Süresi (saniye)'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='Başlangıç Süresi (saniye)'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/', verbose_name='Video Dosyası'),
            preserve_default=False,
        ),
    ]
