# Generated by Django 5.1.2 on 2024-11-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_videogallery_video_url_videogallery_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='cover_image',
        ),
    ]
