# Generated by Django 5.1.2 on 2024-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_content_alter_ekip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dernek Adı')),
                ('member_number', models.CharField(max_length=50, verbose_name='Dernek Üye Numarası')),
                ('logo', models.ImageField(upload_to='association_logos/', verbose_name='Dernek Logosu')),
            ],
            options={
                'verbose_name': 'Dernek',
                'verbose_name_plural': 'Dernek',
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousel'},
        ),
        migrations.AlterModelOptions(
            name='i̇zleyizi',
            options={'verbose_name': 'Web Site Trafiği', 'verbose_name_plural': 'Web Site Trafiği'},
        ),
    ]
