# Generated by Django 5.1.2 on 2024-11-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_association_alter_content_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'Mesajlar',
                'verbose_name_plural': 'Mesajlar',
            },
        ),
    ]
