# Generated by Django 5.1.2 on 2024-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
    ]
