# Generated by Django 5.1.2 on 2024-11-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_contact_options_rename_text_contact_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
