# Generated by Django 5.1.2 on 2024-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_mymodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', models.TextField()),
                ('resim', models.ImageField(upload_to='hakkimizda_resim/')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
